apiVersion: v1
entries:
  flowforge:
  - apiVersion: v2
    appVersion: 1.10.0
    created: "2023-09-07T11:39:44.241971-05:00"
    dependencies:
    - condition: forge.localPostgresql
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.14.0
    description: FlowForge
    digest: 3d3e4f50d35ca011ca77f6576b5ede89ae899794e4fbd3e56dff51cda07fd579
    home: https://flowforge.com
    icon: https://flowforge.com/apple-touch-icon.png
    keywords:
    - flowforge
    - node-red
    maintainers:
    - name: FlowForge Inc
      url: https://flowforge.com
    name: flowforge
    type: application
    urls:
    - https://wizehive.github.io/flowforge-helm/flowforge-1.10.0.tgz
    version: 1.10.0
generated: "2023-09-07T11:39:44.236817-05:00"
